# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Artem's Blog
paginate:       5
baseurl:        "/blog"
url:            "https://chesterhow.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
#markdown:       redcarpet

# About
author:
  name:         Artem Arakcheev
  url:          http://chester.how
  email:        artem.ft at gmail

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/arakcheev

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
